[project]
name = "lecture-9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "openai>=2.6.1",
    "rich>=14.2.0",
]


[tool.uv.workspace]
members = [
    "my_package",
]
