FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8000

# пример для FastAPI (uvicorn). Для Flask будет другая команда.
CMD ["python", "-m", "uvicorn", "main:app", "--host=0.0.0.0", "--port=8000"]